### ISSUE TITLE
Missing unit tests.

### ISSUE THREAD

**Issue by seehait** [seehait/series-renamer-tools#19]

**Comment by michalirak** [comment]
Can I help with this?

**Comment by seehait** [comment]
Sure.

**Comment by georgettica** [comment]
can I take over? it's been a while and I want to give it a go aswell @seehait

**Comment by seehait** [comment]
@georgettica Yes 👍

**Comment by michalirak** [comment]
@seehait You can remove me from the assignees, I am a bit too overwhelmed at the moment to help :\

**Comment by georgettica** [comment]
I am currently trying to figure out pyfakefs. But I will come through the other side soon :)

**Comment by georgettica** [comment]
@seehait you can see the PR @Ta-D did

**Comment by seehait** [comment]
@georgettica I put some comments :)

**Comment by Tal-D** [comment]
Added changes according to the comments. @seehait  @georgettica

**Comment by georgettica** [comment]
Seems like it's going along nicely :) glad it's getting pushed forward @Tal-D @seehait
